export const RoadbookEventType = {
  START: "start",
  FINISH: "finish",
  STRAIGHT: "straight",
  BEAR_LEFT: "bear_left",
  BEAR_RIGHT: "bear_right",
  LEFT_90: "left_90",
  RIGHT_90: "right_90",
  SHARP_LEFT: "sharp_left",
  SHARP_RIGHT: "sharp_right",
  HAIRPIN_LEFT: "hairpin_left",
  HAIRPIN_RIGHT: "hairpin_right",
  FORK_LEFT: "fork_left",
  FORK_RIGHT: "fork_right",
  TJUNCTION_LEFT: "tjunction_left",
  TJUNCTION_RIGHT: "tjunction_right",
  CROSSROAD: "crossroad",
  GATE: "gate",
  WATER: "water",
  CREST: "crest",
  DIP: "dip",
  CONTROL: "control",
  DANGER_1: "danger_1",
  DANGER_2: "danger_2",
  DANGER_3: "danger_3",
  NOTE: "note",
}

export function createEmptyRoadbookRow() {
  return {
    index: 0,
    kmTotal: 0,
    kmPartial: 0,
    lat: null,
    lon: null,
    eventType: null,
    tulipTemplate: null,
    bearingIn: null,
    bearingOut: null,
    angle: null,
    icon: null,
    notes: "",
    source: "derived",
    confidence: 0,
    linkedWaypointIds: [],
  }
}
