[build]
  publish = "."

[[redirects]]
  from = "/guide"
  to = "https://outrageous-cheese-c1f.notion.site/RouteMapper-User-Guide-3caff8d3fef281fba88cff44a1d7424f"
  status = 302
  force = true

[[redirects]]
  from = "/user-guide"
  to = "https://outrageous-cheese-c1f.notion.site/RouteMapper-User-Guide-3caff8d3fef281fba88cff44a1d7424f"
  status = 302
  force = true

[[redirects]]
  from = "/travel-guide"
  to = "https://routemapper.notion.site/go-routemapper-net-guide-38f87469a8ea80a6aea2ec9f022189c5"
  status = 302
  force = true

[[redirects]]
  from = "/go-guide"
  to = "https://routemapper.notion.site/go-routemapper-net-guide-38f87469a8ea80a6aea2ec9f022189c5"
  status = 302
  force = true
